# Generated by Django 5.0.6 on 2024-05-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='user',
        ),
        migrations.RemoveField(
            model_name='touravailability',
            name='user',
        ),
    ]
