# Generated by Django 5.0.6 on 2024-06-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_remove_image_user_remove_itinerary_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
